<?php
// AnimateCSS Control
return array(
      'type' => 'group',
      'heading' => __( 'UXF Dashed' ),
      'options' => array(
        'dashed' => array(
          'type'    => 'slider',
          'heading' => __( 'Width' ),
          'unit' => 'px',
          'max'        => 20,
          'min'        => 0,
          'step'       => 1,
        ),
        'dashed_spacing' => array(
          'conditions' => 'dashed',
          'type'    => 'slider',
          'heading' => __( 'Spacing' ),
          'default'    => '2',
          'unit' => '+',
          'max'        => 31,
          'min'        => 0,
          'step'       => 1,
        ),
        'dashed_radius' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type' => 'slider',
          'heading' => __('Radius'),
          'default' => 0,
          'unit' => 'px',
          'max' => 50,
          'min' => 0,
        ),
        'dashed_color' => array(
          'conditions' => 'dashed',
          'type' => 'colorpicker',
          'heading' => __('Color'),
          'default' => '',
          'format' => 'rgb',
          'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
        ),
        'dashed_gradient' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type' => 'colorpicker',
          'heading' => __('Color Gradient'),
          'default' => '',
          'format' => 'rgb',
          'helpers'  => require( get_template_directory() . '/inc/builder/shortcodes/helpers/colors.php' ),
        ),
        'dashed_length' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type'    => 'slider',
          'heading' => __( 'Dash Length' ),
          'default'    => '1',
          'unit' => '+',
          'max'        => 30,
          'min'        => 1,
          'step'       => 1,
        ),
        'dashed_slanting' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type'    => 'slider',
          'heading' => __( 'Slanting Angle' ),
          'default'    => '-60',
          'unit' => '+',
          'max'        => 60,
          'min'        => -60,
          'step'       => 1,
        ),
        'dashed_fade' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type'    => 'slider',
          'heading' => __( 'Fade' ),
          'unit' => '+',
          'default'    => '1',
          'max'        => 1,
          'min'        => 0,
          'step'       => 0.01,
        ),
        'dashed_diraction'      => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type'    => 'checkbox',
          'heading' => 'Flip diraction',
        ),
        'dashed_animation' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
          'type'    => 'slider',
          'heading' => __( 'Animation' ),
          'unit' => 's',
          'max'        => 1,
          'min'        => 0,
          'step'       => 0.1,
        ),
        'dashed_visibility' => array(
          'conditions' => 'dashed && dashed_spacing != "0"',
             'type' => 'select',
             'heading' => __('Visibility'),
             'default'    => '',
             'config'  => array(
               'placeholder' => __( 'Select...', 'ux-builder' ),
               'multiple'    => true,
               'options' => array(
                   'top'  => 'Top',
                   'left'  => 'Left',
                   'right'  => 'Right',
                   'bottom'  => 'Bottom',
               ),
             ),
         ),
),
);